### PR TITLE
Site/2019

### PR DESCRIPTION
**Pull request by WillPower264**
It's been a while since pushing to gh-pages

### CODE REVIEW

**Comment by dfan** [comment]
Huge :P

**Comment by dfan** [comment]
lgtm as long as you made sure you updated the docs in the repo not just on the website

**Review by dfan — APPROVED** [review]
Huge :P lgtm as long as you're sure the pdf files are updated on the repo not just the website

**Comment by WillPower264** [comment]
> Huge :P lgtm as long as you're sure the pdf files are updated on the repo not just the website

Yeah they're always consistent

**Pull request merged**
